### ISSUE TITLE
Error: The terraform-provider-google-beta_v5.20.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by Dipanshi293** [GoogleCloudPlatform/cloud-foundation-fabric#2153]
Hi Team

When I launched the apply for creating new GKE cluster I received a provider error in all modules (autopilot, standard, nodepool). We are referring Cloud Foundation Fabric modules (autopilot, standard, nodepool) version 29.

**Terraform Version**
```
Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.20.0
+ provider registry.terraform.io/hashicorp/google-beta v5.20.0
```
**Affected Resource(s)**
```
google_container_cluster
```
**Expected behavior**
Terraform plan and apply should be executed as expected.

**Actual Behavior**
```
│   23: resource "google_container_cluster" "cluster" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
 
Stack trace from the terraform-provider-google-beta_v5.20.0_x5 plugin:
 
panic: interface conversion: interface {} is nil, not map[string]interface {}
 
goroutine 214 [running]:
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/container.expandAuthenticatorGroupsConfig(...)
        github.com/hashicorp/terraform-provider-google-beta/google-beta/services/container/resource_container_cluster.go:4704
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/container.resourceContainerClusterCreate(0x0?, {0x4071ec0?, 0xc000484800})
        github.com/hashicorp/terraform-provider-google-beta/google-beta/services/container/resource_container_cluster.go:2317 +0x5af7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x4855a18?, {0x4855a18?, 0xc00105d7d0?}, 0xd?, {0x4071ec0?, 0xc000484800?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00109a8c0, {0x4855a18, 0xc00105d7d0}, 0xc001108f70, 0xc002046780, {0x4071ec0, 0xc000484800})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000746498, {0x4855a18?, 0xc00105d680?}, 0xc001ba0be0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x4855970?, {0x4855a18?, 0xc00105d350?}, 0xc001ba0be0)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00055f680, {0x4855a18?, 0xc00105c960?}, 0xc001b90a80)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x400aa80?, 0xc00055f680}, {0x4855a18, 0xc00105c960}, 0xc002138b00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c1800, {0x4855a18, 0xc00105c8d0}, {0x485ffb8, 0xc001121040}, 0xc00016d200, 0xc00071e300, 0x6380118, 0x0)
        google.golang.org/grpc@v1.61.1/server.go:1385 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc0001c1800, {0x485ffb8, 0xc001121040}, 0xc00016d200)
        google.golang.org/grpc@v1.61.1/server.go:1796 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.1/server.go:1029 +0x91
created by google.golang.org/grpc.(*Server).serveStreams.func2
        google.golang.org/grpc@v1.61.1/server.go:1040 +0x145
 
Error: The terraform-provider-google-beta_v5.20.0_x5 plugin crashed!
 
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
 
Operation failed: failed running terraform apply (exit 1)
```
**Steps to Reproduce**
terraform init
terraform apply

**Comment by juliocc** [comment]
Please share your code. In any case, this looks like a provider issue.

**Comment by Dipanshi293** [comment]
FYI - same error in both versions (v29 and v29)
**Autopilot code:** 
```
**main.tf**

module "gke_cluster_autopilot" {
  source              = "git::https://github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/gke-cluster-autopilot?ref=v29.0.0"
  name                = "sample-autopilot-cluster"
  project_id          = "project-1"
  location            = "us-central-1"
  labels              = {team = team1}
  deletion_protection = false
  vpc_config = {
    network    = "vpc-shared-network1"
    subnetwork = "us-central-1-dev"
    secondary_range_names = {
      pods     = "us-central-1-pods"
      services = "us-central-1-services"
    }
    master_ipv4_cidr_block   = "172.0.0.0/28"
    master_authorized_ranges = {
	sample-vms = "100.32.0.0/10"
  }
 
  private_cluster_config = {
    enable_private_nodes    = true
    enable_private_endpoint = true
    master_global_access    = false
  }
 
  enable_addons = {
    cloudrun                       = false
    config_connector               = false
    dns_cache                      = true
    horizontal_pod_autoscaling     = true
    http_load_balancing            = true
    gce_persistent_disk_csi_driver = true
    gcp_filestore_csi_driver       = true
  }
 
  enable_features = {
    binary_authorization = true
    cost_management      = true
    shielded_nodes       = true
    dns = {
      provider = "CLOUD-DNS"
      scope    = "CLUSTER-SCOPE"
      domain   = "<DOMAIN>"
    }
    database_encryption = {
      state    = "ENCRYPTED"
      key_name = "<KEY_NAME>"
    }
    workload_identity    = true
    l4_ilb_subsetting    = true
    groups_for_rbac      = "<groupforrbac>"
    dataplane_v2         = true
    gateway_api          = true
    intranode_visibility = true
    network_policy       = true
  }
 
  node_config = {
    service_account          = "<sa-account>"
    issue_client_certificate = false
    release_channel          = "REGULAR"
    tags                     = "<tags>"
    boot_disk_kms_key        = "<boot-disk-key-key>"
  }
 
  issue_client_certificate = false
  release_channel          = "REGULAR"
 
  logging_config = {
    enable_api_server_logs         = true
    enable_scheduler_logs          = true
    enable_controller_manager_logs = true
  }
 
  monitoring_config = {
    enable_api_server_metrics         = true
    enable_controller_manager_metrics = true
    enable_scheduler_metrics          = true
    enable_daemonset_metrics          = true
    enable_deployment_metrics         = true
    enable_hpa_metrics                = true
    enable_pod_metrics                = true
    enable_statefulset_metrics        = true
    enable_storage_metrics            = true
    enable_managed_prometheus = true
  }
 
   backup_configs = {
    enable_backup_agent = true
    backup_plans = {
      nightly = {
        region                = "us-central-1"
        schedule              = "0 3 * * *"
        encryption_key        = "<encryption-key>"
        include_secrets       = true
        include_volume_data   = true
        retention_policy_days = "7"
      }
    }
  }
}
```
**Standard Code** 
```
**main.tf** 

module "gke_cluster_standard" {
  source              = "git::https://github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/gke-cluster-standard?ref=v29.0.0"
   name                = "sample-standard-cluster"
  project_id          = "project-1"
  location            = "us-central-1"
  labels              = {team = team1}
  deletion_protection = false
  vpc_config = {
    network    = "vpc-shared-network1"
    subnetwork = "us-central-1-dev"
    secondary_range_names = {
      pods     = "us-central-1-pods"
      services = "us-central-1-services"
    }
    master_ipv4_cidr_block   = "172.0.0.0/28"
    master_authorized_ranges = {
	sample-vms = "100.32.0.0/10"
  }

 
  private_cluster_config = {
    enable_private_nodes    = true
    enable_private_endpoint = true
    master_global_access    = false
  }
 
  enable_addons = {
    cloudrun                       = false
    config_connector               = false
    dns_cache                      = true
    horizontal_pod_autoscaling     = true
    http_load_balancing            = true
    gce_persistent_disk_csi_driver = true
    gcp_filestore_csi_driver       = true
  }
 
  enable_features = {
    binary_authorization = true
    cost_management      = true
    shielded_nodes       = true
    dns = var.dns_provider != "PLATFORM_DEFAULT" ? {
      provider = "CLOUD-DNS"
      scope    = "CLUSTER-SCOPE"
      domain   = "<DOMAIN>"
    } : null
    database_encryption = {
      state    = "ENCRYPTED"
      key_name = "<KEY_NAME>"
    }
    workload_identity    = true
    l4_ilb_subsetting    = true
    groups_for_rbac      = "<groupforrbac>"
    dataplane_v2         = true
    gateway_api          = true
    intranode_visibility = true
    network_policy       = true
  }
 
  cluster_autoscaling = {
    autoscaling_profile = "BALANCED"
    auto_provisioning_defaults = {
      boot_disk_kms_key = ""
      disk_size         = null
      disk_type         = "pd-standard"
      image_type        = "COS_CONTAINERD"
      #oauth_scopes      = []
      service_account = ""
      shielded_instance_config = {
        integrity_monitoring = true
        secure_boot          = true
      }
      management = {
        auto_repair  = true
        auto_upgrade = true
    } }
    cpu_limits = {
      min = 1
      max = 64
    }
    mem_limits = {
      min = 1
      max = 512
    }
  }
 
  node_config = {
    tags              = "<TAGS>"
    service_account   = "<sa-account>"
    boot_disk_kms_key = "<boot_disk_kms_key>"
  }
  issue_client_certificate = false
  release_channel          = "REGULAR"
  max_pods_per_node        = 32
 
  # Logging and monitoring
  logging_config = {
    enable_api_server_logs         = true
    enable_scheduler_logs          = true
    enable_controller_manager_logs = true
    enable_system_logs             = true
    enable_workloads_logs          = true
  }
 
  monitoring_config = {
    enable_api_server_metrics         = true
    enable_controller_manager_metrics = true
    enable_scheduler_metrics          = true
    enable_daemonset_metrics          = true
    enable_deployment_metrics         = true
    enable_hpa_metrics                = true
    enable_pod_metrics                = true
    enable_statefulset_metrics        = true
    enable_storage_metrics            = true
 
    enable_managed_prometheus = true
  }
 
  # Backup for GKE
  backup_configs = {
    enable_backup_agent = true
    backup_plans = {
      nightly = {
        region                = "us-central-1"
        schedule              = "0 3 * * *"
        encryption_key        = "<encryption-key>"
        include_secrets       = true
        include_volume_data   = true
        retention_policy_days = "7"
      }
    }
  }
}
```
**Nodepool Code**
```
main.tf

module "gke-nodepool" {
  source       = "git::https://github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/gke-nodepool?ref=v29.0.0"
  project_id   = "project-1"
  cluster_name = "sample-standard-cluster-1"
  location     = "us-central-1"
  name         = "sample-nodepool-1"
  labels       = {team = team1}
  tags         = "<tags>"
  service_account = {
    create       = false
    email        = "<sa-account>"
    oauth_scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }
  node_config = {
    machine_type = "n2-standard-2"
    disk_size_gb = 50
    disk_type    = "pd-ssd"
    shielded_instance_config = {
      enable_secure_boot          = true
      enable_integrity_monitoring = true
    }
    sandbox_config_gvisor         = true
    boot_disk_kms_key             = "<boot_disk_kms_key>"
    workload_metadata_config_mode = "GKE_METADATA"
  }
  nodepool_config = {
    autoscaling = {
      max_node_count = 10
      min_node_count = 1
    }
    management = {
      auto_repair = true
      auto_upgrade = true
    }
  }
}
```

**Comment by Dipanshi293** [comment]
Hi @juliocc ,I wanted to check in on the progress of this issue. Any update?
Thanks!

**Comment by rosmo** [comment]
It's related to `groups_for_rbac` parameter in `enable_features`, are you passing just a string to it? If so, what's that string?

**Comment by Dipanshi293** [comment]
Hi @rosmo 

In main.tf, we are passing: groups_for_rbac = var.groups_for_rbac
And in variable.tf , we are passing default ="" , so they can decide and provide their group for rbac

variable "groups_for_rbac" {
description = "Role-Based Access Control (RBAC) is used to manage and control access to resources by assigning roles to users, groups, or service accounts."
  type        = string
  default     = ""
}

**Comment by rosmo** [comment]
Set `default = null` and you should be good.

**Comment by Dipanshi293** [comment]
Hi @rosmo 
Issue is resolved. Thanks!
